# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pdpgr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pdpgr
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  rn_path = "../node_modules/react-native"
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'pdpgrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # very important to have, unless you removed React dependencies for Libraries 
  # and you rely on Cocoapods to manage it
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end

